### ISSUE TITLE
An unhandled exception has occurred while executing the request: at the Miscellaneous.ResolveBVN(string bvn)

### ISSUE THREAD

**Issue by ddynamight** [adebisi-fa/paystack-dotnet#17]
Hi @adebisi-fa,

Thanks for the response and for making our work easier with the library, I hope your weekend was great. The **v0.7.6** did fixed the previous problems. But I have another issue with the BvnResolve endpoint.

When called like this:

`var bvnDetailsResult = payApi.Miscellaneous.ResolveBVN(request.Bvn);`

**with request.Bvn being a string**

Please see error below.

> **An unhandled exception has occurred while executing the request.
> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
>    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
>    at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
>    at PayStack.Net.PayStackApi.ParseAndResolveMetadata[TR](String& rawJson)
>    at PayStack.Net.PayStackApi.Get[TR](String relativeUrl)**

_Originally posted by @ddynamight in https://github.com/adebisi-fa/paystack-dotnet/issues/16#issuecomment-529353389_

**Comment by ddynamight** [comment]
@adebisi-fa, Can you please respond when you see this.
I need this ASAP. I need to know if I am the one doing something wrong on my end.
As this is the delaying our release. Kindly save a product. :(

**Comment by adebisi-fa** [comment]
Dear @ddynamight,

Sorry for the delay.  I was off these last two days.

I'll review the code and revert, asap.

Cheers!
